<?php
// Public PDF download endpoint — serves uploaded PDFs with proper headers.
// No auth required; only serves files matching the pdf_ upload pattern.

$filename = basename($_GET['file'] ?? '');

// Only serve files generated by the blog PDF uploader
if (!$filename || !preg_match('/^pdf_[a-zA-Z0-9._-]+\.pdf$/i', $filename)) {
    http_response_code(400);
    exit('Invalid request.');
}

$filepath = __DIR__ . '/../../storage/uploads/' . $filename;

if (!file_exists($filepath) || !is_file($filepath)) {
    http_response_code(404);
    exit('File not found.');
}

// Optional friendly download name passed by the inserter
$downloadName = basename($_GET['name'] ?? $filename);
if (!preg_match('/\.pdf$/i', $downloadName)) {
    $downloadName .= '.pdf';
}

header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="' . str_replace('"', '', $downloadName) . '"');
header('Content-Length: ' . filesize($filepath));
header('Cache-Control: private, max-age=86400');
header('X-Content-Type-Options: nosniff');
readfile($filepath);
exit;
